rules:
  bungeecord:
    server_name: '-0'
  # - true: feature is enable (by default)
  # - false: feature is disabled (prevent)
  features:
    custom_config:
      enable: true  # enable individual config
      default_value: false  # default value if the custom config is turned off
    damages:
      pvp: true
      pve: true
      fall: true
      explosion: true
      fire: true
      drowning: true
    player:
      food_loss: true
      bubble_loss: true
    build:
      place: true
      break: true
    interactions:
      world:
        doors: true
        trap_doors: true
        fence_gates: true
        buttons: true
        levers: true
        pressure_plates: true
      inventory:
        click: true
        drop: true
        pickup: true
        swap: true
  locations:
    y_limit: '-0'
  events:
    login:
      tp_to_spawn: false
      intro:
        sound: '-0'
        private_message: '-0'
        title:
          value: '-0'
          subtitle: '-0'
          timings: # in milliseconds
            fade_in: 200
            persistence: 1000
            fade_out: 200
      item:
        texture: '-0'
        name: '-0'

spawn:
  world: 'world'
  point:
    x: 0
    y: 100
    z: 0
  facing:
    yaw: 0
    pitch: 0